[workspace]
resolver = "2"
members = ["common", "btree", "parser", "row", "engine", "runner"]

[workspace.dependencies]
thiserror = "2.0"
uuid = { version = "1.20", features = ["v4"] }
tempfile = "3.24.0"
