[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
parser = { path = "../parser" }
row = { path = "../row" }
common = { path = "../common" }
btree = { path = "../btree" }

[dev-dependencies]
tempfile = { workspace = true }
